### ISSUE TITLE
Issue in converting the instance segmentation mask encoding from bdd100k to coco 

### ISSUE THREAD

**Issue by sfarkya04** [bdd100k/bdd100k#206]
Hello, 

I am trying to convert the bdd100k instance segmentation using this command: 
`python3 -m bdd100k.label.to_coco -m ins_seg --only-mask -i ./bdd100k/labels/ins_seg/bitmasks/val -o ./ins_seg_val_cocofmt_v2.json`

Also, tried this: 
`python3 -m bdd100k.label.to_coco -m ins_seg -i ./bdd100k/labels/ins_seg/polygons/ins_seg_val.json -o ./ins_seg_val_cocofmt_v3.json -mb ./bdd100k/labels/ins_seg/bitmasks/val`

The conversion is successful in both cases and the annotation looks like this 

![Screen Shot 2022-01-07 at 11 46 36 AM](https://user-images.githubusercontent.com/75509659/148577201-4e07622b-9e0f-495d-a2d8-004deabb623e.png)
** that's not how coco annotations are.

Now, if you see the segmentation field above there's string encoding of the masks. Now, I am unsure if that's expected or not. 

Further, assuming it's correct,  I tried to load the annotations using loader from DETR https://github.com/facebookresearch/detr/blob/091a817eca74b8b97e35e4531c1c39f89fbe38eb/datasets/coco.py#L36 

The line I have mentioned above is supposed to do the conversion but I am getting an error from the pycocotools that it's not expecting a string in the mask. 
![Screen Shot 2022-01-07 at 11 53 51 AM](https://user-images.githubusercontent.com/75509659/148578244-bcb1d369-4b04-493d-a68c-0dd82563f771.png)

So, I am unsure where the problem is? Is the conversion correct to coco then the loader should work? 
Note: I tried to convert the detections and they worked fine. 

Thank you for any help you can provide.

**Comment by thomasehuang** [comment]
Hello,

COCO supports many representations of masks, including polygons and RLE. The one we are using is RLE, which is a compact representation to avoid storing the entire mask. This is because we cannot convert bitmasks to polygons. From the error, it looks like your dataloader only can handle COCO polygons. There are two solutions:
1. Load the bitmasks directly as an image.
2. Use the below code to generate the mask given the RLE:
```python
from pycocotools import mask as mask_utils
mask = mask_utils.decode(segmentation)
```

They will both return the same mask, but both requires you to change the dataloader code, unfortunately.

Hope that helps.

**Comment by sfarkya04** [comment]
@thomasehuang Thank you so much! that works alright.
