### ISSUE TITLE
cannot import name 'NPROC' from 'scalabel.common.parallel'

### ISSUE THREAD

**Issue by samerrkhann** [bdd100k/bdd100k#212]
Hey there!
While running the script to convert the annotation from bdd100k format to COCO the following exception is being raised. cannot import name 'NPROC' from 'scalabel.common.parallel'. What is the possible solution for the problem?

**Comment by fyu** [comment]
It may be solved with installing the scalabel package with `pip install -U git+https://github.com/scalabel/scalabel.git`

**Comment by samerrkhann** [comment]
> It may be solved with installing the scalabel package with `pip install -U git+https://github.com/scalabel/scalabel.git`

The problem stands still. Still it says missing maybe the authors of scalable has removed it. Anyways, just a suggestion, it would be a great help if you guys can pull off a complete guide on how to use these pre-trained model just out of the box. Hope to see that addition soon.

**Comment by pupu-chenyanyan** [comment]
@samerrkhann Hello ,did you saved this problem?I have the same problem with you .

**Comment by samerrkhann** [comment]
> @samerrkhann Hello ,did you saved this problem?I have the same problem with you .

Not really. The problem stands still.

**Comment by tobiasfshr** [comment]
This is hardly possible since NPROC is clearly in the code of the current master branch of scalabel https://github.com/scalabel/scalabel/blob/d2b1c03d887c39bf767057eba5b2727ecc2f3d35/scalabel/common/parallel.py#L21
you should try to 
1. remove scalabel from your env
2. clone the current master branch of scalabel
3. install it locally with python setup.py install

**Comment by pupu-chenyanyan** [comment]
@tobiasfshr  thanks you very much,I saved this problem as you describe.
